### ISSUE TITLE
큰 텍스처 파일이 들어왔을때 double->int 변환로직에 오류가 있어 의도하지 않은 계산결과같이 나오는 버그

### ISSUE THREAD

**Issue by CodyKat** [Oris482/Cub3d#36]
그냥 double을 int로 강제캐스팅하면 소수부가 버려지도록 되는데, 텍스처파일이 크면 이때 음수값으로 계산되는 경우가 있는 버그가 있음.

**Comment by Oris482** [comment]
4k 파일이여도 3~4천대 아닌가요?? 왜 음수로 들어가지

**Comment by CodyKat** [comment]
찍어야되는 픽셀을  double에서 그냥 대충 캐스팅으로 소수점 버림을 했는데 그게 문제가 되었네요
