### ISSUE TITLE
loop에서 game->map에 접근불가 문제

### ISSUE THREAD

**Issue by CodyKat** [Oris482/Cub3d#9]
mlx_loop_hook에서 실행하는 main_loop안에서 game구조체 안에 있는 map에 접근할때 segfault가 뜸
print_map함수로 map을 찍으려해도 0번인덱스에서 부터 실패

**Comment by Oris482** [comment]
map은 game.info.map 에서 꺼내 써야됩니다. 구조체에 **map 두 개 있길래 하나 지우려다가 쓰려고 만들어뒀나 싶어서 따로 안건드렸습니다. print_game_info 함수에서 map 제대로 저장됐는지 출력하면서 확인되고 있음
